# Generated by Django 3.1.1 on 2020-09-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank='', default='', max_length=200, null=True),
        ),
    ]
